version: '2'
services:
    cpmtsht-app:
        image: cpmtsht
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://cpmtsht-mariadb:3306/cpmtsht
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cpmtsht-mariadb:
        extends:
            file: mariadb.yml
            service: cpmtsht-mariadb
